FROM archlinux:latest
RUN ["/bin/bash", "-c", "pacman --noconfirm -Syyu \
    pacman --noconfirm -S base-devl bash git vim sudo curl gnupg wget \
    && locale-gen en_US.UTF-8"]
# xorg-server-xvfb python python-pip go jdk-openjdk jre-openjdk
