services:
  nextapp:
    container_name: nextapp
    image: []
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - goapp
    environment:
  goapp:
    container_name: goapp
    image: []
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
